name: GEX Cloud Bot

on:
  schedule:
    - cron: '*/30 13-21 * * 1-5'
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install pandas selenium
          mkdir -p ./GEX_Data

      - name: Executar o Motor Black-Scholes
        run: python gex_profile_v7_cloud.py

      - name: Salvar Planilhas (GitHub Artifacts)
        uses: actions/upload-artifact@v4
        with:
          name: GEX_Data_Planilhas
          path: ./GEX_Data/*.csv
          retention-days: 5
